//
// Created by DELL on 2020-03-22.
//

#ifndef LEXICAL_ANALYZER_GENERATOR_TEST_COMPONENTS_H
#define LEXICAL_ANALYZER_GENERATOR_TEST_COMPONENTS_H
void test1_components ();
#endif //LEXICAL_ANALYZER_GENERATOR_TEST_COMPONENTS_H
